#############################################################################
# Makefile for building: map_bsg
# Generated by qmake (2.01a) (Qt 4.7.0) on: Tue Feb 22 00:11:38 2011
# Project:  map_bsg.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile map_bsg.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -std=c++0x -Werror -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = file_parser.cpp \
		main.cpp \
		mc_variable.cpp \
		minecraft_byte_array.cpp \
		minecraft_object.cpp \
		thread.cpp \
		block_comp.cpp moc_thread.cpp
OBJECTS       = file_parser.o \
		main.o \
		mc_variable.o \
		minecraft_byte_array.o \
		minecraft_object.o \
		thread.o \
		block_comp.o \
		moc_thread.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		map_bsg.pro
QMAKE_TARGET  = map_bsg
DESTDIR       = 
TARGET        = map_bsg

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: map_bsg.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile map_bsg.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile map_bsg.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/map_bsg1.0.0 || $(MKDIR) .tmp/map_bsg1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/map_bsg1.0.0/ && $(COPY_FILE) --parents file_parser.h mc_list.h mc_variable.h minecraft_byte_array.h minecraft_object.h thread.h block_comp.h .tmp/map_bsg1.0.0/ && $(COPY_FILE) --parents file_parser.cpp main.cpp mc_variable.cpp minecraft_byte_array.cpp minecraft_object.cpp thread.cpp block_comp.cpp .tmp/map_bsg1.0.0/ && (cd `dirname .tmp/map_bsg1.0.0` && $(TAR) map_bsg1.0.0.tar map_bsg1.0.0 && $(COMPRESS) map_bsg1.0.0.tar) && $(MOVE) `dirname .tmp/map_bsg1.0.0`/map_bsg1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/map_bsg1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_thread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_thread.cpp
moc_thread.cpp: block_comp.h \
		thread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) thread.h -o moc_thread.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

file_parser.o: file_parser.cpp file_parser.h \
		../map_reader/minecraft_byte_array.h \
		../map_reader/mc_variable.h \
		../map_reader/mc_list.h \
		../map_reader/mc_hash.h \
		../map_reader/minecraft_object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file_parser.o file_parser.cpp

main.o: main.cpp thread.h \
		block_comp.h \
		../map_reader/minecraft_object.h \
		../map_reader/mc_variable.h \
		../map_reader/mc_list.h \
		../map_reader/mc_hash.h \
		file_parser.h \
		../map_reader/minecraft_byte_array.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mc_variable.o: mc_variable.cpp ../map_reader/mc_variable.h \
		../map_reader/mc_list.h \
		../map_reader/mc_hash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mc_variable.o mc_variable.cpp

minecraft_byte_array.o: minecraft_byte_array.cpp ../map_reader/minecraft_byte_array.h \
		../map_reader/mc_variable.h \
		../map_reader/mc_list.h \
		../map_reader/mc_hash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraft_byte_array.o minecraft_byte_array.cpp

minecraft_object.o: minecraft_object.cpp ../map_reader/minecraft_object.h \
		../map_reader/mc_variable.h \
		../map_reader/mc_list.h \
		../map_reader/mc_hash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minecraft_object.o minecraft_object.cpp

thread.o: thread.cpp ../map_reader/minecraft_object.h \
		../map_reader/mc_variable.h \
		../map_reader/mc_list.h \
		../map_reader/mc_hash.h \
		thread.h \
		block_comp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thread.o thread.cpp

block_comp.o: block_comp.cpp block_comp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o block_comp.o block_comp.cpp

moc_thread.o: moc_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_thread.o moc_thread.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

